/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz3;

import quiz3.menu.Menu;

public class App {

    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.render();
    }
}
